services:
    RavenFlux\VairogsHelper\Date\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Email\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\File\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Generator\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Gravatar\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Http\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Iter\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Json\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Php\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Sort\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Text\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Uri\Extension:
        public: false
        tags:
            -
                name: twig.extension

    RavenFlux\VairogsHelper\Util\Extension:
        public: false
        tags:
            -
                name: twig.extension
