on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: splitsh-lite
    steps:
      - name: Get branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: branch
      - name: Deploy
        id: deploy
        uses: vairogs/deploy-action@master
        env:
          BRANCH: ${{ steps.branch.outputs.branch }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMPONENTS_URL: ${{ secrets.COMPONENTS_URL }}
